Update pcdata-manager

diff --git a/pcdata-manager b/pcdata-manager
--- a/pcdata-manager
+++ b/pcdata-manager
@@ -11,7 +11,7 @@ manager_path="/usr/bin/pcdata-manager"
 pcdata_update () {
 
 echo -e "${yellow}\nDownloading and installing the new PCData version...${nocolor}"
-wget -q -O "$pcdata_path" "$pcdata_url"
+wget -q -O "$pcdata_path" "$pcdata_url" || { echo "Update failed! Check your connection."; exit 1; }
 chmod +x "$pcdata_path"
 echo -e "${green}\nPCData is updated!\n${nocolor}"
 
