Add tmux configuration download and uninstall support

diff --git a/pcdata-manager b/pcdata-manager
--- a/pcdata-manager
+++ b/pcdata-manager
@@ -24,6 +24,8 @@ pcdata_url="https://raw.githubusercontent.com/JediFonseca/pcdata/refs/heads/main
 pcdata_path="/usr/bin/pcdata"
 pcdata_main_url="https://raw.githubusercontent.com/JediFonseca/pcdata/refs/heads/main/pcdata-main"
 pcdata_main_path="/usr/bin/pcdata-main"
+tmux_config_url="https://raw.githubusercontent.com/JediFonseca/pcdata/refs/heads/main/pcdata.tmux.conf"
+tmux_config_path="/usr/share/pcdata.tmux.conf"
 manager_path="/usr/bin/pcdata-manager"
 
 pcdata_update () {
@@ -31,6 +33,7 @@ pcdata_update () {
 echo -e "${yellow}\nDownloading and installing the new PCData version...${nocolor}"
 wget -q -O "$pcdata_main_path" "$pcdata_main_url" || { echo "Update failed! Check your connection."; exit 1; }
 wget -q -O "$pcdata_path" "$pcdata_url" || { echo "Update failed! Check your connection."; exit 1; }
+wget -q -O "$tmux_config_path" "$tmux_config_url" || { echo "Update failed! Check your connection."; exit 1; }
 chmod +x "$pcdata_main_path"
 echo -e "${green}\nPCData is updated!\n${nocolor}"
 
@@ -42,6 +45,7 @@ echo -e "${yellow}\nUninstalling PCData...${nocolor}"
 rm -f "$pcdata_main_path" &> /dev/null
 rm -f "$pcdata_path" &> /dev/null
 rm -f "$manager_path" &> /dev/null
+rm -f "$tmux_config_path" &> /dev/null
 echo -e "${green}\nPCData is uninstalled!\n${nocolor}"
 
 }
