Update pcdata installation script for new components

diff --git a/pcdata-install b/pcdata-install
--- a/pcdata-install
+++ b/pcdata-install
@@ -24,11 +24,15 @@ yellow='\033[1;33m'
 red='\033[0;31m'
 nocolor='\033[0m'
 
-pcdata_location="/usr/bin/pcdata"
+pcdata_main_location="/usr/bin/pcdata-main"
 pcdata_manager_location="/usr/bin/pcdata-manager"
+pcdata_location="/usr/bin/pcdata"
+tmux_config_location="/usr/share/pcdata.tmux.conf"
 
-pcdata_url="https://raw.githubusercontent.com/JediFonseca/pcdata/refs/heads/main/pcdata"
+tmux_config_url="https://github.com/JediFonseca/pcdata/blob/main/pcdata.tmux.conf"
+pcdata_main_url="https://raw.githubusercontent.com/JediFonseca/pcdata/refs/heads/main/pcdata-main"
 pcdata_manager_url="https://raw.githubusercontent.com/JediFonseca/pcdata/refs/heads/main/pcdata-manager"
+pcdata_url="https://raw.githubusercontent.com/JediFonseca/pcdata/refs/heads/main/pcdata"
 
 # Safety --------------------------------------------------------------------------------#
 
@@ -51,6 +55,7 @@ declare -A debian_dependencies_list=(
 ["iproute2"]="IP Route"
 ["usbutils"]="USB Utils"
 ["curl"]="curl"
+["tmux"]="Tmux"
 
 )
 
@@ -66,6 +71,7 @@ declare -A arch_dependencies_list=(
 ["iproute2"]="IP Route"
 ["usbutils"]="USB Utils"
 ["curl"]="curl"
+["tmux"]="Tmux"
 
 )
 
@@ -81,6 +87,7 @@ declare -A fedora_dependencies_list=(
 ["iproute"]="IP Route"
 ["usbutils"]="USB Utils"
 ["curl"]="curl"
+["tmux"]="Tmux"
 
 )
 
@@ -136,9 +143,11 @@ echo -e "${blue}1. Install the dependencies:${nocolor}"
 [[ $distroid == "arch" ]] && echo "${pacman//,/, }" | fold -s -w 90
 [[ $distroid == "fedora" ]] && echo "${dnf//,/, }" | fold -s -w 90
 echo
-echo -e "${blue}2. Download 'pcdata' and 'pcdata-manager' to '/usr/bin'.${nocolor}"
+echo -e "${blue}2. Download 'pcdata', 'pcdata-main' and 'pcdata-manager' to '/usr/bin'.${nocolor}"
 echo
-echo -e "${blue}3. Give 'pcdata' and 'pcdata-manager' execution permissions with 'chmod +x'.${nocolor}"
+echo -e "${blue}3. Download 'pcdata.tmux.conf' to '/usr/share/'.${nocolor}"
+echo
+echo -e "${blue}4. Give 'pcdata', 'pcdata-main' and 'pcdata-manager' execution permissions with 'chmod +x'.${nocolor}"
 echo
 echo -e -n "${yellow}\nPress ENTER to install PCData or CTRL+C to cancel.${nocolor}"
 read -r < /dev/tty
@@ -181,8 +190,10 @@ fi
 
 download_scripts () {
 
-wget --show-progress -O "$pcdata_location" "$pcdata_url" || { echo "pcdata download failed! Check your connection."; exit 1; }
+wget --show-progress -O "$pcdata_main_location" "$pcdata_main_url" || { echo "pcdata-main download failed! Check your connection."; exit 1; }
 wget --show-progress -O "$pcdata_manager_location" "$pcdata_manager_url" || { echo "pcdata-manager download failed! Check your connection."; exit 1; }
+wget --show-progress -O "$pcdata_location" "$pcdata_url" || { echo "pcdata download failed! Check your connection."; exit 1; }
+wget --show-progress -O "$tmux_config_location" "$tmux_config_url" || { echo "pcdata.tmux.config download failed! Check your connection."; exit 1; }
 
 }
 
@@ -190,8 +201,9 @@ wget --show-progress -O "$pcdata_manager_location" "$pcdata_manager_url" || { ec
 
 execution_permissions () {
 
-chmod +x "$pcdata_location"
+chmod +x "$pcdata_main_location"
 chmod +x "$pcdata_manager_location"
+chmod +x "$pcdata_location"
 
 }
 
